@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/clock>
!include <tupadr3/font-awesome-5/calendar_alt>

skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam defaultTextAlignment center


scale 1200*480

file DiscountEligibilityDate #MediumPurple [
 <size:60><$clock></size>
 **DiscountEligibilityDate**
....
6 months of service
]

file DiscountBecameEffective #Orange [
 <size:60><$clock></size>
 **DiscountBecameEffective**
]


DiscountEligibilityDate -> DiscountBecameEffective

@enduml