@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/clock>
!include <tupadr3/font-awesome-5/calendar_alt>
!include <tupadr3/font-awesome-5/gripfire>

skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam defaultTextAlignment center


scale 2200*2480

frame **Whenever** #MediumPurple {
    file EmployeeJoined #Orange [
        **EmployeeJoined**
    ....
        employeeId
    ]

    file CreateDiscount #DeepSkyBlue [
        **CreateDiscount**
    ....
        employeeId
    ]
}

file Discount1 #Yellow [
    <<aggregate>>
    **Discount**
]

file Discount2 #Yellow [
    **Discount**
    <<aggregate>>
---
    **DiscountEligibility**
....
   is discount eligibility date reached?
]

file DiscountCreated #Orange [
    **DiscountCreated**
....
    employeeId
    eligibilityDate
]

file DiscountAssociated #Orange [
    **DiscountAssociated**
....
    employeeId
    accountId
]

    file DiscountAccountSystem #IMPLEMENTATION [
        **DiscountAccountSystem**
    ]


EmployeeJoined -> CreateDiscount
CreateDiscount -> Discount1
Discount1 -> DiscountCreated

frame **DiscountEligibilityProcessManager** #MediumPurple {
    file CreateDiscountAccount #DeepSkyBlue [
        1.
        <$clock>
        **CreateDiscountAccount**
    ]



    file AssociateDiscount #DeepSkyBlue [
        2.
        **AssociateDiscount**
    ....
        accountId
    ]

    DiscountCreated -D-> CreateDiscountAccount
    CreateDiscountAccount "1." ---R-> DiscountAccountSystem
    DiscountAccountSystem "On failure:\nEligibilityDate + 1" .L.> CreateDiscountAccount
    CreateDiscountAccount "2." --> AssociateDiscount
    AssociateDiscount "3." -D-> Discount2
}


Discount2 -> DiscountAssociated



@enduml