@startuml
skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent


!include components.iuml

scale 1200*4800

EmployeeWorkCycleContext -R--> BenefitsContext

EmployeeWorkCycleContext -D- EmployeeJoined

BenefitsContext -D- DiscountAssociated


@enduml