@startuml
skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent




file EmployeeChangedDepartment #Orange [
    **EmployeeChangedDepartment**
....
    occurred: 2020-03-01
    applies: 2020-05-01
]


@enduml