@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/clock>
!include <tupadr3/font-awesome-5/calendar_alt>
!include <tupadr3/font-awesome-5/gripfire>

skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam defaultTextAlignment center


scale 1200*480

file DiscountEligibilityDate #MediumPurple [
 <size:60><$clock></size>
 **DiscountEligibilityDate**
....
6 months of service
]

file DiscountBecameEffective #Orange [
 <size:60><$clock></size>
 **DiscountBecameEffective**
]

file DiscountAssociated #Orange [
 **DiscountAssociated**
]

file DiscountAccountSystem #IMPLEMENTATION [
    **DiscountAccountSystem**
]

file CreateDiscountAccount #DeepSkyBlue [
    **CreateDiscountAccount**
]

DiscountEligibilityDate -> DiscountBecameEffective
DiscountBecameEffective  -D- "1." CreateDiscountAccount
CreateDiscountAccount "2." -> DiscountAccountSystem
CreateDiscountAccount "3." -D- DiscountAssociated


@enduml