@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/clock>
!include <tupadr3/font-awesome-5/calendar_alt>
!include <tupadr3/font-awesome-5/gripfire>

skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam defaultTextAlignment center


scale 1200*480


file DiscountCreated #Orange [
    **DiscountCreated**
]

file DiscountRefreshed #Orange [
    **DiscountRefreshed**
]


file Discount #Yellow [
    **Discount**
    <<aggregate>>
---
    **EffectiveDiscount**
....
   is Discount effective?
]

frame **FinancialYearEndProcessManager** #MediumPurple {
    file RefreshDiscount #DeepSkyBlue [
        <$clock>
        **RefreshDiscount**
    ]


    DiscountCreated -R-> RefreshDiscount
}

RefreshDiscount --R--> Discount
Discount -> DiscountRefreshed


@enduml