@startuml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/clock>
!include <tupadr3/font-awesome-5/calendar_alt>
!include <tupadr3/font-awesome-5/gripfire>

skinparam defaultFontName Purisa
skinparam handwritten true
skinparam backgroundcolor transparent

skinparam defaultTextAlignment center


scale 1200*480


storage EmployeeWorkCycleContext #Moccasin
storage BenefitsContext #SandyBrown

file EmployeeMarkedAsLeaver #Orange [
    **EmployeeMarkedAsLeaver**
....
    leavingDate
]

rectangle "ACL\n<<Event Scheduler>>" #SandyBrown {


file EmployeeLeft #Orange [
    <$clock>
    **EmployeeLeft**
]

file ScheduleEvent #DeepSkyBlue [
    **ScheduleEvent**
....
    leavingDate
]

EmployeeWorkCycleContext -> EmployeeMarkedAsLeaver
EmployeeMarkedAsLeaver -> ScheduleEvent
ScheduleEvent -> EmployeeLeft
EmployeeLeft -> BenefitsContext

}
@enduml